name: Node
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Deno
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: |
          npm ci
          npm run test
          npm run build
